name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["18", ">=20"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
